/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lecture2;

/**
 *
 * @author user
 */
public class SimpleSocietyChooser extends javax.swing.JFrame {

    /**
     * Creates new form SimpleSocietyChooser
     */
    public SimpleSocietyChooser() {
        initComponents();
        setLocationRelativeTo(null);
        listHolder.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtons = new javax.swing.ButtonGroup();
        musicAndDance = new javax.swing.JRadioButton();
        literature = new javax.swing.JRadioButton();
        sport = new javax.swing.JRadioButton();
        cV = new javax.swing.JRadioButton();
        question = new javax.swing.JLabel();
        youMightEnjoy = new javax.swing.JLabel();
        listHolder = new javax.swing.JScrollPane();
        outputList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interests");
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        radioButtons.add(musicAndDance);
        musicAndDance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        musicAndDance.setText("Music and Dance");
        musicAndDance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicAndDanceActionPerformed(evt);
            }
        });

        radioButtons.add(literature);
        literature.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        literature.setText("Literature");
        literature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literatureActionPerformed(evt);
            }
        });

        radioButtons.add(sport);
        sport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sport.setText("Sport");
        sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportActionPerformed(evt);
            }
        });

        radioButtons.add(cV);
        cV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cV.setText("Things that look good on a CV");
        cV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVActionPerformed(evt);
            }
        });

        question.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question.setText("What are you interested in?");

        youMightEnjoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        listHolder.setBorder(null);
        listHolder.setOpaque(false);

        outputList.setColumns(20);
        outputList.setEditable(false);
        outputList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outputList.setRows(5);
        outputList.setBorder(null);
        outputList.setOpaque(false);
        listHolder.setViewportView(outputList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(youMightEnjoy, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(musicAndDance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(literature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(sport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(listHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question)
                    .addComponent(youMightEnjoy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(musicAndDance)
                        .addGap(18, 18, 18)
                        .addComponent(literature)
                        .addGap(18, 18, 18)
                        .addComponent(sport)
                        .addGap(18, 18, 18)
                        .addComponent(cV))
                    .addComponent(listHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {question, youMightEnjoy});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayClubs(String ... clubs) {
        youMightEnjoy.setText("You might enjoy...");
        listHolder.setVisible(true);
        String output ="";
        for (String club : clubs)
            output = output + club + '\n';
        outputList.setText(output);
    }

    private void musicAndDanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicAndDanceActionPerformed
        displayClubs("Belly Dance", "Bluegrass and Folk", "Capoeira", "Ceilidh",
                "Cheerleaders");
    }//GEN-LAST:event_musicAndDanceActionPerformed

    private void literatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literatureActionPerformed
        displayClubs("Anime", "Book Club", "Comic Book Society");
    }//GEN-LAST:event_literatureActionPerformed

    private void sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportActionPerformed
       displayClubs("Aikido", "American Football", "Archery",
               "Athletics & Cross Country", "Badminton", "Basketball (Men's)",
               "Basketball (Women's)", "Boxing",  "Canoeing", "Caving",
               "Cricket (Men's)", "Cricket (Women's)", "Cycling/Mountian Biking");
    }//GEN-LAST:event_sportActionPerformed

    private void cVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVActionPerformed
        displayClubs("Canvas", "Commercial Services Committee",
                "Conservation Volunteers");
    }//GEN-LAST:event_cVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleSocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleSocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleSocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleSocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SimpleSocietyChooser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cV;
    private javax.swing.JScrollPane listHolder;
    private javax.swing.JRadioButton literature;
    private javax.swing.JRadioButton musicAndDance;
    private javax.swing.JTextArea outputList;
    private javax.swing.JLabel question;
    private javax.swing.ButtonGroup radioButtons;
    private javax.swing.JRadioButton sport;
    private javax.swing.JLabel youMightEnjoy;
    // End of variables declaration//GEN-END:variables
}
