/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lecture2;

import java.util.EnumSet;

/**
 *
 * @author user
 */
public class SocietyChooser extends javax.swing.JFrame {

    /**
     * Creates new form SimpleSocietyChooser
     */
    public SocietyChooser() {
        initComponents();
        setLocationRelativeTo(null);
        holder.setVisible(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instruction = new javax.swing.JLabel();
        youMightEnjoy = new javax.swing.JLabel();
        suggestButton = new javax.swing.JButton();
        exerciseBox = new javax.swing.JCheckBox();
        outdoorsBox = new javax.swing.JCheckBox();
        cvBox = new javax.swing.JCheckBox();
        musicBox = new javax.swing.JCheckBox();
        readingBox = new javax.swing.JCheckBox();
        holder = new javax.swing.JScrollPane();
        outputList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interests");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        instruction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instruction.setText("Click on everything you are interested in and then press this button");

        youMightEnjoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        suggestButton.setBackground(new java.awt.Color(204, 255, 204));
        suggestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suggestButton.setText("Suggest something");
        suggestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestButtonActionPerformed(evt);
            }
        });

        exerciseBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exerciseBox.setText("Get exercise");
        exerciseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerciseBoxActionPerformed(evt);
            }
        });

        outdoorsBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outdoorsBox.setText("Do something outdoors");
        outdoorsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outdoorsBoxActionPerformed(evt);
            }
        });

        cvBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cvBox.setText("Do something that looks good on a CV");
        cvBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvBoxActionPerformed(evt);
            }
        });

        musicBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        musicBox.setText("Enjoy music");
        musicBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBoxActionPerformed(evt);
            }
        });

        readingBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        readingBox.setText("Enjoy literature");
        readingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readingBoxActionPerformed(evt);
            }
        });

        holder.setBorder(null);
        holder.setEnabled(false);
        holder.setFocusable(false);
        holder.setOpaque(false);

        outputList.setColumns(20);
        outputList.setEditable(false);
        outputList.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        outputList.setRows(5);
        outputList.setBorder(null);
        outputList.setOpaque(false);
        holder.setViewportView(outputList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suggestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exerciseBox)
                    .addComponent(cvBox)
                    .addComponent(musicBox)
                    .addComponent(readingBox)
                    .addComponent(outdoorsBox))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(youMightEnjoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instruction)
                    .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exerciseBox)
                        .addGap(18, 18, 18)
                        .addComponent(outdoorsBox)
                        .addGap(18, 18, 18)
                        .addComponent(readingBox)
                        .addGap(13, 13, 13)
                        .addComponent(cvBox)
                        .addGap(18, 18, 18)
                        .addComponent(musicBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(youMightEnjoy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void suggestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestButtonActionPerformed
        //Find the intersection
        EnumSet<Club> suggestion = EnumSet.allOf(Club.class);
        if  (  exerciseImportant  )  suggestion.retainAll(exerciseClubs);
        if  (  outdoorsInportant  )  suggestion.retainAll(outdoorsClubs);
        if  (  cvImportant  )  suggestion.retainAll(cvClubs);
        if  (  musicImportant  )  suggestion.retainAll(musicClubs);
        if  (  booksImportant  )  suggestion.retainAll(literatureClubs);

        if  (  suggestion.isEmpty()  )  {
            //Find the union
            suggestion = EnumSet.noneOf(Club.class);
            if  (  exerciseImportant  )  suggestion.addAll(exerciseClubs);
            if  (  outdoorsInportant  )  suggestion.addAll(outdoorsClubs);
            if  (  cvImportant  )  suggestion.addAll(cvClubs);
            if  (  musicImportant  )  suggestion.addAll(musicClubs);
            if  (  booksImportant  )  suggestion.addAll(literatureClubs);
            youMightEnjoy.setText("There is no perfect club but you might enjoy...");
        }
        else
            youMightEnjoy.setText("You might enjoy...");
        holder.setVisible(true);
        String output ="";
        for (Club club : suggestion)
            output = output + club + '\n';
        output = output.toLowerCase().replaceAll("_"," ");
        outputList.setText(output);
    }//GEN-LAST:event_suggestButtonActionPerformed

    boolean exerciseImportant = false;
    EnumSet <Club> exerciseClubs = EnumSet.of(Club.AIKIDO, Club.AMERICAN_FOOTBALL,
            Club.ARCHERY, Club.ATHLETICS, Club.BADMINTON,  Club.BASKETBALL_MENS,
            Club.BASKETBALL_WOMENS,  Club.BELLY_DANCE, Club.BOXING,
            Club.CANOEING, Club.CAPOEIRA,  Club.CAVING, Club.CEILIDH,
            Club.CHEERLEADERS, Club.CONSERVATION, Club.CRICKET_MENS,
            Club.CRICKET_WOMENS, Club.CYCLING );
    private void exerciseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciseBoxActionPerformed
        exerciseImportant = ! exerciseImportant;
    }//GEN-LAST:event_exerciseBoxActionPerformed

    boolean outdoorsInportant = false;
    EnumSet <Club> outdoorsClubs = EnumSet.of(Club.CANOEING, Club.CANVAS,
            Club.CAVING, Club.CONSERVATION, Club.CYCLING );
    private void outdoorsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outdoorsBoxActionPerformed
        outdoorsInportant = ! outdoorsInportant;
    }//GEN-LAST:event_outdoorsBoxActionPerformed

    boolean cvImportant = false;
    EnumSet <Club> cvClubs = EnumSet.of(Club.CANVAS, Club.COMMERCIAL_SERVICES,
            Club.CONSERVATION);
    private void cvBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvBoxActionPerformed
        cvImportant = !cvImportant;
    }//GEN-LAST:event_cvBoxActionPerformed

    boolean musicImportant = false;
    EnumSet <Club> musicClubs = EnumSet.of(Club.BELLY_DANCE, Club.BLUEGRASS,
            Club.CAPOEIRA, Club.CEILIDH);
    private void musicBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBoxActionPerformed
        musicImportant = ! musicImportant;
    }//GEN-LAST:event_musicBoxActionPerformed

    boolean booksImportant = false;
    EnumSet <Club> literatureClubs = EnumSet.of(Club.ANIME, Club.BOOK,
            Club.COMIC_BOOK);
    private void readingBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readingBoxActionPerformed
        booksImportant = ! booksImportant;
    }//GEN-LAST:event_readingBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocietyChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SocietyChooser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cvBox;
    private javax.swing.JCheckBox exerciseBox;
    private javax.swing.JScrollPane holder;
    private javax.swing.JLabel instruction;
    private javax.swing.JCheckBox musicBox;
    private javax.swing.JCheckBox outdoorsBox;
    private javax.swing.JTextArea outputList;
    private javax.swing.JCheckBox readingBox;
    private javax.swing.JButton suggestButton;
    private javax.swing.JLabel youMightEnjoy;
    // End of variables declaration//GEN-END:variables
}
