/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legorob;
import ShefRobot.*;
/**
 *
 * @author eia14hx Hao Xu
 */
public class RobGuiClass extends javax.swing.JFrame {

        Robot myRobot = new Robot();
       // Motor leftMotor = myRobot.getLargeMotor(Motor.Port.B);
       // Motor rightMotor = myRobot.getLargeMotor(Motor.Port.C);
       // Speaker speaker = myRobot.getSpeaker();
       // Motor rotor = myRobot.getLargeMotor(Motor.Port.D);
        Movement move = new Movement();
    public RobGuiClass() {
        initComponents();
        move.initial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        welcomeText = new javax.swing.JLabel();
        ForwardButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        RotorLeftButton = new javax.swing.JButton();
        RotorRightButton = new javax.swing.JButton();
        LittleupButton = new javax.swing.JButton();
        movingspeedtext = new javax.swing.JTextField();
        MovingSpeedButton = new javax.swing.JButton();
        rotorspeedbutton = new javax.swing.JButton();
        rotorspeedtext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeText.setText("Welcome to the Lego EX3 control panel");

        ForwardButton.setText("Forward");
        ForwardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ForwardButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ForwardButtonMouseReleased(evt);
            }
        });
        ForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Backward");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        LeftButton.setText("Left");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RightButton.setText("Right");
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        RotorLeftButton.setText("LeftRotate");
        RotorLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotorLeftButtonActionPerformed(evt);
            }
        });

        RotorRightButton.setText("RightRotate");
        RotorRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotorRightButtonActionPerformed(evt);
            }
        });

        LittleupButton.setText("up little");
        LittleupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LittleupButtonActionPerformed(evt);
            }
        });

        movingspeedtext.setText("Speed type in here");

        MovingSpeedButton.setText("Change Moving Speed");
        MovingSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovingSpeedButtonActionPerformed(evt);
            }
        });

        rotorspeedbutton.setText("Change Rotor Speed");
        rotorspeedbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotorspeedbuttonActionPerformed(evt);
            }
        });

        rotorspeedtext.setText("Speed type in here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LittleupButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LeftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RightButton)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RotorLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RotorRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(StopButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ForwardButton)
                                .addComponent(welcomeText))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MovingSpeedButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(movingspeedtext)))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rotorspeedtext))
                                    .addComponent(rotorspeedbutton))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovingSpeedButton)
                    .addComponent(rotorspeedbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movingspeedtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotorspeedtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(LittleupButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ForwardButton)
                    .addComponent(RotorLeftButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton)
                    .addComponent(RightButton)
                    .addComponent(RotorRightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton)
                .addGap(38, 38, 38)
                .addComponent(StopButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        @SuppressWarnings("empty-statement")
    private void ForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardButtonActionPerformed
              ;// TODO add your handling code here:
    }//GEN-LAST:event_ForwardButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        if (BackButton.isEnabled()){           
            
            move.Backward();
        }// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        
        
        
        if (StopButton.isEnabled()){
            
           
            move.stop();
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_StopButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        if (LeftButton.isEnabled()){
            move.left();
        }// TODO add your handling code here:
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        if (RightButton.isEnabled()){
            move.right();
        }    
    }//GEN-LAST:event_RightButtonActionPerformed

    private void RotorLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotorLeftButtonActionPerformed
       
        if(RotorLeftButton.isEnabled()){
                
              move.rotorleft();
                
                
                
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RotorLeftButtonActionPerformed

    private void RotorRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotorRightButtonActionPerformed
       if(RotorRightButton.isEnabled()){
                
          move.rotorright();
       }// TODO add your handling code here:
    }//GEN-LAST:event_RotorRightButtonActionPerformed

    private void LittleupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LittleupButtonActionPerformed
         if(LittleupButton.isEnabled()){
            move.rotorup();
        }/// TODO add your handling code here:
    }//GEN-LAST:event_LittleupButtonActionPerformed

    private void ForwardButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForwardButtonMousePressed
            move.Forward(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_ForwardButtonMousePressed

    private void ForwardButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForwardButtonMouseReleased
            move.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ForwardButtonMouseReleased

    private void MovingSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovingSpeedButtonActionPerformed
        if(MovingSpeedButton.isEnabled()){
            move.setMovingSpeed(Integer.valueOf(movingspeedtext.getText()));
        }// TODO add your handling code here// TODO add your handling code here:
    }//GEN-LAST:event_MovingSpeedButtonActionPerformed

    private void rotorspeedbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotorspeedbuttonActionPerformed
        if (rotorspeedbutton.isEnabled()) {
            move.setRotorSpeed(Integer.valueOf(rotorspeedtext.getText()));
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rotorspeedbuttonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RobGuiClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RobGuiClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RobGuiClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RobGuiClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RobGuiClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ForwardButton;
    private javax.swing.JButton LeftButton;
    private javax.swing.JButton LittleupButton;
    private javax.swing.JButton MovingSpeedButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JButton RotorLeftButton;
    private javax.swing.JButton RotorRightButton;
    private javax.swing.JButton StopButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField movingspeedtext;
    private javax.swing.JButton rotorspeedbutton;
    private javax.swing.JTextField rotorspeedtext;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
